[build]
  base = "client"                 # <-- set base to client
  publish = "dist/public"         # <-- where Vite will output
  command = "npm install && npm run build"

[functions]
  directory = "dist/functions"    # if you have serverless functions
