[build]
  # Base directory is root because vite.config.ts is there
  base = "."
  # Install dependencies and build
  command = "npm install && npm run build"
  # Publish folder is the output of Vite
  publish = "dist/public"
  # Functions directory if you have serverless functions
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  port = 8888
